name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write **/*.{yml,yaml,md,js,jsx,json}
          commit_message: 🤖 Enforce Code Style
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: YamlLint
        run: yamllint .

  gh-pages:
    needs: prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.JS
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create .nojekyll file
        run: touch out/.nojekyll
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: '🤖 Deploy static site for change: {msg}'
          SKIP_EMPTY_COMMITS: true
