name: Continuous Integration

'on':
  push:
    branches:
      - main

jobs:
  prettify-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write .
          commit_message: 🤖 Enforce Code Style
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          yamllint_flags: '.'
          fail_on_error: true
          level: warning

  gh-pages:
    needs: prettify-lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create .nojekyll file
        run: touch build/.nojekyll
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: '🤖 Deploy static site for change: {msg}'
          SKIP_EMPTY_COMMITS: true
