name: CI - Push

'on':
  push:
    branches:
      - main

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - id: yamllint
        name: Yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          yamllint_flags: '.'
          fail_on_error: true
          filter_mode: nofilter

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - id: eslint
        name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          eslint_flags: --ext js,jsx .
          fail_on_error: true
          filter_mode: nofilter

  prettier:
    name: Prettier - Enforce code style
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - id: prettier
        name: Prettier
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write .
          commit_message: 🤖 Enforce Code Style
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  gh-pages:
    name: Deploy to GH Pages
    needs:
      - yamllint
      - eslint
      - prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create .nojekyll file
        run: touch build/.nojekyll
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: '🤖 Deploy static site for change: {msg}'
          SKIP_EMPTY_COMMITS: true
