name: Continuous Integration - PR

'on':
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          yamllint_flags: '.'
          fail_on_error: true
          level: warning
      - if: always()
        name: ESLint
        run: npx eslint --ext js,jsx --fix .
      - if: always()
        name: Code suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: eslint
