name: Issues & PRs label management

on: [issue_comment]

jobs:
  # Remove 'status: waiting for feedback' label once a user comments on an issue or PR currently marked as waiting for feedback
  remove_feedback_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'status: waiting for feedback'